/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author segessemann
 */
public class ReadMail extends javax.swing.JFrame {

    /**
     * Creates new form ReadMail
     */
    public ReadMail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jToolBarHeader = new javax.swing.JToolBar();
        jButtonReply = new javax.swing.JButton();
        jButtonForward = new javax.swing.JButton();
        jButtonDeleteMail = new javax.swing.JButton();
        jButtonAddToFolder = new javax.swing.JButton();
        jScrollPaneMailText = new javax.swing.JScrollPane();
        jTextAreaMailText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Read Mail");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(915, 584));

        jPanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jToolBarHeader.setFloatable(false);
        jToolBarHeader.setRollover(true);
        jToolBarHeader.setBorderPainted(false);
        jToolBarHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonReply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/back.png"))); // NOI18N
        jButtonReply.setText("  reply  ");
        jButtonReply.setFocusable(false);
        jButtonReply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReply.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReplyActionPerformed(evt);
            }
        });
        jToolBarHeader.add(jButtonReply);

        jButtonForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/forward.png"))); // NOI18N
        jButtonForward.setText("forward");
        jButtonForward.setFocusable(false);
        jButtonForward.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonForward.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForwardActionPerformed(evt);
            }
        });
        jToolBarHeader.add(jButtonForward);

        jButtonDeleteMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delMail.png"))); // NOI18N
        jButtonDeleteMail.setText("delete Mail");
        jButtonDeleteMail.setFocusable(false);
        jButtonDeleteMail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDeleteMail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarHeader.add(jButtonDeleteMail);

        jButtonAddToFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/toFolder.png"))); // NOI18N
        jButtonAddToFolder.setText("add to folder");
        jButtonAddToFolder.setFocusable(false);
        jButtonAddToFolder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddToFolder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAddToFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddToFolderActionPerformed(evt);
            }
        });
        jToolBarHeader.add(jButtonAddToFolder);

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextAreaMailText.setColumns(20);
        jTextAreaMailText.setRows(5);
        jScrollPaneMailText.setViewportView(jTextAreaMailText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneMailText, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneMailText, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddToFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddToFolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddToFolderActionPerformed

    private void jButtonForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForwardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonForwardActionPerformed

    private void jButtonReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddToFolder;
    private javax.swing.JButton jButtonDeleteMail;
    private javax.swing.JButton jButtonForward;
    private javax.swing.JButton jButtonReply;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPaneMailText;
    private javax.swing.JTextArea jTextAreaMailText;
    private javax.swing.JToolBar jToolBarHeader;
    // End of variables declaration//GEN-END:variables
}
